/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neaproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author amakod
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    
    
    private static String driverClass = "com.mysql.jdbc.Driver";
    private static String url = "jdbc:mysql://localhost:3306/nea_db";
    private static String username = "root";
    private static String dpassword = "bball616.DAS";
    
    
    
    
    public SignIn() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditEmail = new javax.swing.JTextField();
        BtnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EditPassword = new javax.swing.JPasswordField();
        BtnRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EditEmail.setForeground(new java.awt.Color(153, 153, 153));
        EditEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EditEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EditEmailFocusLost(evt);
            }
        });
        EditEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmailActionPerformed(evt);
            }
        });

        BtnLogin.setText("Login");
        BtnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Brand");

        EditPassword.setToolTipText("");
        EditPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EditPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EditPasswordFocusLost(evt);
            }
        });
        EditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPasswordActionPerformed(evt);
            }
        });

        BtnRegister.setText("Register");
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        jLabel3.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(BtnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnLogin)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditPasswordActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        
        


        boolean contin = true;
        boolean success = false;
        
        String usernamee = EditEmail.getText();
        String password = EditPassword.getText();
            
        /*
        
        try {
            Class.forName(driverClass);
            Connection con = DriverManager.getConnection(url,username,dpassword);
            
            usernamee = EditEmail.getText();
            password = EditPassword.getText();
            
            Statement stm = con.createStatement();
            String sql = "SELECT email, password FROM UserAccounts WHERE (email = '"+usernamee+"') AND (password = '"+password+"')";
            ResultSet rs = stm.executeQuery(sql);
            
            if (rs.next()) {
                dispose();
                Homepage log = new Homepage();
                log.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Email and Password Incorrect..");
                EditEmail.setText("");
                EditPassword.setText("");
            }
            
            con.close();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        */
        
        if (password.isEmpty() || usernamee.equalsIgnoreCase("email")) {
            contin = false;
        }
        

        
        JavaHttpClientRECIVE con = new JavaHttpClientRECIVE();
        
        String Data = (con.ClientR("useraccounts"));
        
        String[] words = Data.split("\\s+");
        
        for (int i = 0; i < words.length; i++) {
            
            words[i] = words[i].replaceAll("[^\\w]", " ");
            
            String[] W = words[i].split(" ");
            
            for(int j = 0; j < W.length;j++){
                if (usernamee.equalsIgnoreCase(W[j]) && contin == true) {
                    for (int k = 0; k < W.length; k++) {
                        contin = false;
                        if (password.equalsIgnoreCase(W[k])) {
                            System.out.println(";"+W[k]+";");
                            success = true;
                            dispose();
                            Homepage log = new Homepage();
                            log.setVisible(true);
                            
                            
                        }
                    }
                }
            }
            
        
        
        }
        System.out.println("e");
        if (success == false) {
          JOptionPane.showMessageDialog(this, "Email and Password Incorrect..");
                EditEmail.setText("");
                EditPassword.setText("");  
        }
        
        
         
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void EditEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditEmailActionPerformed

    private void EditEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EditEmailFocusGained
        if(EditEmail.getText().equals("Email")){
            EditEmail.setText("");
            EditEmail.setForeground (new Color(0,0,0));
        }
    }//GEN-LAST:event_EditEmailFocusGained

    private void EditEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EditEmailFocusLost
        if(EditEmail.getText().equals("")){
          EditEmail.setText("Email");
          EditEmail.setForeground (new Color(153,153,153));
      }
    }//GEN-LAST:event_EditEmailFocusLost

    private void EditPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EditPasswordFocusGained
        if(EditPassword.getText().equals("Password")){
            EditPassword.setText("");
            EditPassword.setForeground (new Color(0,0,0));
        }
    }//GEN-LAST:event_EditPasswordFocusGained

    private void EditPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EditPasswordFocusLost
        if(EditPassword.getText().equals("")){
          EditPassword.setText("Password");
          EditPassword.setForeground (new Color(153,153,153));
      }
    }//GEN-LAST:event_EditPasswordFocusLost

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        Registration log = new Registration();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnRegister;
    private javax.swing.JTextField EditEmail;
    private javax.swing.JPasswordField EditPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
